apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    name: frontend
spec:
  selector:
    name: master1
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort