apiVersion: v1
kind: Service
metadata:
  name: console
  labels:
    name: console
spec:
  selector:
    name: master
  ports:
    - port: 50070
      targetPort: 50070
      name: hadoop
    - port: 7070
      targetPort: 7070
      name: kylin
  type: NodePort