apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    name: backend
spec:
  selector:
    name: master
  ports:
    - port: 8083
      targetPort: 8083
      nodePort: 31960
  type: NodePort