apiVersion: v1
kind: Service
metadata:
  name: hadoop
  labels:
    name: hadoop
spec:
  selector:
    name: master
  ports:
    - port: 50070
      targetPort: 50070
      nodePort: 30070
  type: NodePort