apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  clusterIP: None # headless service
  ports:
    - port: 80
      name: web


---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx # match .spec.template.metadata.labels
  serviceName: "nginx"  #这里和Headless Service绑定了
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      terminationGracePeriodSeconds: 10 # ???
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              name: web




