apiVersion: v1
kind: Service
metadata:
  name: nodered
  labels:
    name: nodered
spec:
  selector:
    name: master1
  ports:
    - port: 1880
      targetPort: 1880
      nodePort: 31880
  type: NodePort