apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvtest
  labels:
    pv: pv1
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data/k8s/test
    server: 172.17.45.74



